name: Overwolf

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '>=14.18.0'

      - name: Install dependencies
        run: npm install
        working-directory: ./overwolf
         
      - name: Linter
        run: npm run lint
        working-directory: ./overwolf
      
      - name: Build
        run: npm run build
        working-directory: ./overwolf
        
